In [41]:
import pandas as pd
import numpy as np
 

df =pd.read_csv("F:\PYTHON PROJ\LEARN PYTHON\Customer Churn Prediction\WA_Fn-UseC_-Telco-Customer-Churn.csv")
df = df.drop(columns='customerID')
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Main takeaway from last part:
The feature might be included in the ML
1. 'Contract'
2. 'MonthlyCharges'
3. 'InternetService'
4. 'PaymentMethod'

1. Handle Missing Values

1.1 Checking hidden missing values

in the TotalCharges col, the data type is str, it is possible the blank data " " is not treated as NaN

In [42]:
df['TotalCharges'].isin(["", " ", "NA", "null"]).sum()

np.int64(11)

We checked that there are 11 cells missing value. For TotalCharges, we need the data type to be numeric. By converting it, the missing value will be NaN

1.2 Convert hidden missng value

In [43]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'], errors='coerce')

In [44]:
df.TotalCharges.info

<bound method Series.info of 0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64>

1.3 Check missing values
now the col is changed to float and the missing value is NaN.

In [45]:
df['TotalCharges'].isin(["", " ", "NA", "null"]).sum()

np.int64(0)

1.4  Fill missing values (median)
Median is robust to outliers

In [46]:
df['TotalCharges'] =df.TotalCharges.fillna(df.TotalCharges.median())

df['TotalCharges']

df['SeniorCitizen'] = pd.to_numeric(df['SeniorCitizen'])

Step 2. Data Type Standardization.

In [47]:
df =df.convert_dtypes()

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   string
 1   SeniorCitizen     7043 non-null   Int64
 2   Partner           7043 non-null   string
 3   Dependents        7043 non-null   string
 4   tenure            7043 non-null   Int64
 5   PhoneService      7043 non-null   string
 6   MultipleLines     7043 non-null   string
 7   InternetService   7043 non-null   string
 8   OnlineSecurity    7043 non-null   string
 9   OnlineBackup      7043 non-null   string
 10  DeviceProtection  7043 non-null   string
 11  TechSupport       7043 non-null   string
 12  StreamingTV       7043 non-null   string
 13  StreamingMovies   7043 non-null   string
 14  Contract          7043 non-null   string
 15  PaperlessBilling  7043 non-null   string
 16  PaymentMethod     7043 non-null   string
 17  MonthlyCharges    7043 non-null   Float64
 18  TotalCharges      7043 non-null   Float64
 19  Churn             7043 non-null   string
dtypes: Float64(2), Int64(2), string(16)
memory usage: 1.1 MB

In [49]:
df['SeniorCitizen'].value_counts()

SeniorCitizen
0    5901
1    1142
Name: count, dtype: Int64

2.2 Idntify the categorical cols

In ML, categorical data cannot be used. Need to be converted to numerical data. Think about logitstic regression

In [50]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

cat_cols

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Churn'],
      dtype='str')

3. Encoding Categorical variable
The feature might be included in the ML 
1. 'Contract'
2. 'MonthlyCharges'
3. 'InternetService'
4. 'PaymentMethod'

those are categorical data

now we can start to covertthe categorical values (use map method)

2.1 binary Categorical data encoding

df['Churn']= df['Churn'].map({'No': 0, 'Yes':1 })
df['Partner']= df['Partner'].map({'No': 0, 'Yes':1 })
df['Dependents'] =df['Dependents'].map({'No': 0, 'Yes':1 })
df['PhoneService'] =df['PhoneService'].map({'No': 0, 'Yes':1 })
df['MultipleLines'] =df['MultipleLines'].map({'No': 0, 'Yes':1 , 'No phone service':0})
df['OnlineSecurity'] =df['OnlineSecurity'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['OnlineBackup'] =df['OnlineBackup'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['DeviceProtection'] =df['DeviceProtection'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['TechSupport'] =df['TechSupport'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['StreamingTV'] =df['StreamingTV'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['StreamingMovies'] =df['StreamingMovies'].map({'No': 0, 'Yes':1 , 'No internet service':0})
df['PaperlessBilling'] =df['PaperlessBilling'].map({'No': 0, 'Yes':1 , 'No internet service':0})

too messy.

In [51]:
df[cat_cols]=df[cat_cols].replace({
    'No internet service': 'No',
    'No phone service':'No'
    })

In [52]:
binary_cols= [col for col in cat_cols if df[col].nunique() ==2]
binary_cols

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'PaperlessBilling',
 'Churn']

In [53]:
binary_cols.remove('gender')
 
df['gender']= df['gender'].map({'Male': 1, 'Female':0 })

turn all binary to numeric 0 1

In [54]:
for col in binary_cols:
    df[col]=df[col].map({'Yes':1, 'No':0})

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   int64
 1   SeniorCitizen     7043 non-null   Int64
 2   Partner           7043 non-null   int64
 3   Dependents        7043 non-null   int64
 4   tenure            7043 non-null   Int64
 5   PhoneService      7043 non-null   int64
 6   MultipleLines     7043 non-null   int64
 7   InternetService   7043 non-null   string
 8   OnlineSecurity    7043 non-null   int64
 9   OnlineBackup      7043 non-null   int64
 10  DeviceProtection  7043 non-null   int64
 11  TechSupport       7043 non-null   int64
 12  StreamingTV       7043 non-null   int64
 13  StreamingMovies   7043 non-null   int64
 14  Contract          7043 non-null   string
 15  PaperlessBilling  7043 non-null   int64
 16  PaymentMethod     7043 non-null   string
 17  MonthlyCharges    7043 non-null   Float64
 18  TotalCharges      7043 non-null   Float64
 19  Churn             7043 non-null   int64
dtypes: Float64(2), Int64(2), int64(13), string(3)
memory usage: 1.1 MB

Step 2.2 Feature engineering

2.2.1 Looks at 'tenure' and 'TotalCharges', we can calculate avg charges every tenure year

In [56]:
df['AvgCharges'] = df['TotalCharges'] / df['tenure'].replace(0,1)

2.2.2 We can further group the customer based on the tenure

In [57]:
df['tenure_group']=pd.cut(df['tenure'], bins=[-1, 6, 12, 24, 36, 60, 72], labels=['0-6m', '6-12m', '1-2y','2-3y','3-5y', '5-6y'])

2.2.3 High Charge indicator

In [58]:

df['high_charge'] = (df['MonthlyCharges'] > df['MonthlyCharges'].median()).astype(int)

2.2.4 Services

In [59]:
services = [
    'PhoneService', 'MultipleLines', 
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies'
]

In [60]:
df['num_of_service'] = df[services].sum(axis=1)

In [61]:
df['num_of_service']

0       1
1       3
2       3
3       3
4       1
       ..
7038    7
7039    6
7040    1
7041    2
7042    6
Name: num_of_service, Length: 7043, dtype: int64

In [62]:
df['num_of_service'] =df['num_of_service']+ (df['num_of_service'] !=0)
df['num_of_service']

0       2
1       4
2       4
3       4
4       2
       ..
7038    8
7039    7
7040    2
7041    3
7042    7
Name: num_of_service, Length: 7043, dtype: int64

export data

In [63]:
df.to_csv("data after ESA.csv", index=False)

2.3 One-Hot Encoding (Multi-category)

In [64]:
cat_cols = df.select_dtypes(include=['object', 'string', 'category']).columns

cat_cols

Index(['InternetService', 'Contract', 'PaymentMethod', 'tenure_group'], dtype='str')

In [65]:
df=pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   Int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   Int64
 5   PhoneService                           7043 non-null   int64
 6   MultipleLines                          7043 non-null   int64
 7   OnlineSecurity                         7043 non-null   int64
 8   OnlineBackup                           7043 non-null   int64
 9   DeviceProtection                       7043 non-null   int64
 10  TechSupport                            7043 non-null   int64
 11  StreamingTV                            7043 non-null   int64
 12  StreamingMovies                        7043 non-null   int64
 13  PaperlessBilling                       7043 non-null   int64
 14  MonthlyCharges                         7043 non-null   Float64
 15  TotalCharges                           7043 non-null   Float64
 16  Churn                                  7043 non-null   int64
 17  AvgCharges                             7043 non-null   Float64
 18  high_charge                            7043 non-null   int64
 19  num_of_service                         7043 non-null   int64
 20  InternetService_Fiber optic            7043 non-null   boolean
 21  InternetService_No                     7043 non-null   boolean
 22  Contract_One year                      7043 non-null   boolean
 23  Contract_Two year                      7043 non-null   boolean
 24  PaymentMethod_Credit card (automatic)  7043 non-null   boolean
 25  PaymentMethod_Electronic check         7043 non-null   boolean
 26  PaymentMethod_Mailed check             7043 non-null   boolean
 27  tenure_group_6-12m                     7043 non-null   bool
 28  tenure_group_1-2y                      7043 non-null   bool
 29  tenure_group_2-3y                      7043 non-null   bool
 30  tenure_group_3-5y                      7043 non-null   bool
 31  tenure_group_5-6y                      7043 non-null   bool
dtypes: Float64(3), Int64(2), bool(5), boolean(7), int64(15)
memory usage: 1.2 MB

In [67]:
bool_cols = df.select_dtypes(include=['boolean']).columns
df[bool_cols] = df[bool_cols].astype(int)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7043 non-null   int64
 1   SeniorCitizen                          7043 non-null   Int64
 2   Partner                                7043 non-null   int64
 3   Dependents                             7043 non-null   int64
 4   tenure                                 7043 non-null   Int64
 5   PhoneService                           7043 non-null   int64
 6   MultipleLines                          7043 non-null   int64
 7   OnlineSecurity                         7043 non-null   int64
 8   OnlineBackup                           7043 non-null   int64
 9   DeviceProtection                       7043 non-null   int64
 10  TechSupport                            7043 non-null   int64
 11  StreamingTV                            7043 non-null   int64
 12  StreamingMovies                        7043 non-null   int64
 13  PaperlessBilling                       7043 non-null   int64
 14  MonthlyCharges                         7043 non-null   Float64
 15  TotalCharges                           7043 non-null   Float64
 16  Churn                                  7043 non-null   int64
 17  AvgCharges                             7043 non-null   Float64
 18  high_charge                            7043 non-null   int64
 19  num_of_service                         7043 non-null   int64
 20  InternetService_Fiber optic            7043 non-null   int64
 21  InternetService_No                     7043 non-null   int64
 22  Contract_One year                      7043 non-null   int64
 23  Contract_Two year                      7043 non-null   int64
 24  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 25  PaymentMethod_Electronic check         7043 non-null   int64
 26  PaymentMethod_Mailed check             7043 non-null   int64
 27  tenure_group_6-12m                     7043 non-null   int64
 28  tenure_group_1-2y                      7043 non-null   int64
 29  tenure_group_2-3y                      7043 non-null   int64
 30  tenure_group_3-5y                      7043 non-null   int64
 31  tenure_group_5-6y                      7043 non-null   int64
dtypes: Float64(3), Int64(2), int64(27)
memory usage: 1.8 MB

In [69]:
df.corr()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_6-12m,tenure_group_1-2y,tenure_group_2-3y,tenure_group_3-5y,tenure_group_5-6y
gender,1.000000,-0.001874,-0.001808,0.010517,0.005106,-0.006488,-0.008414,-0.017021,-0.013773,-0.002105,...,0.008026,-0.003695,0.001215,0.000752,0.013744,0.000139,-0.000701,0.006196,-0.018718,0.016199
SeniorCitizen,-0.001874,1.000000,0.016479,-0.211185,0.016567,0.008576,0.142948,-0.038653,0.066572,0.059428,...,-0.046262,-0.117000,-0.024135,0.171718,-0.153477,-0.014521,0.002144,0.027562,0.010622,-0.002062
Partner,-0.001808,0.016479,1.000000,0.452676,0.379697,0.017706,0.142057,0.143106,0.141498,0.153786,...,0.082783,0.248091,0.082029,-0.083852,-0.095125,-0.095179,-0.048868,0.002744,0.106636,0.279545
Dependents,0.010517,-0.211185,0.452676,1.000000,0.159712,-0.001762,-0.024526,0.080972,0.023671,0.013963,...,0.068368,0.204613,0.060267,-0.150642,0.059071,-0.038428,-0.002443,0.008396,0.040337,0.116656
tenure,0.005106,0.016567,0.379697,0.159712,1.000000,0.008448,0.331941,0.327203,0.360277,0.360653,...,0.202570,0.558533,0.233006,-0.208363,-0.233852,-0.312009,-0.235469,-0.030287,0.361758,0.727136
PhoneService,-0.006488,0.008576,0.017706,-0.001762,0.008448,1.000000,0.279690,-0.092893,-0.052312,-0.071227,...,-0.002791,0.003519,-0.007721,0.003062,-0.003319,-0.002771,0.012473,-0.000646,-0.021395,0.020708
MultipleLines,-0.008414,0.142948,0.142057,-0.024526,0.331941,0.279690,1.000000,0.098108,0.202237,0.201137,...,-0.003794,0.106253,0.060048,0.083618,-0.227206,-0.085634,-0.044828,0.004482,0.078732,0.257768
OnlineSecurity,-0.017021,-0.038653,0.143106,0.080972,0.327203,-0.092893,0.098108,1.000000,0.283832,0.275438,...,0.100162,0.191773,0.115721,-0.112338,-0.080798,-0.080659,-0.055714,-0.017031,0.075824,0.262805
OnlineBackup,-0.013773,0.066572,0.141498,0.023671,0.360277,-0.052312,0.202237,0.283832,1.000000,0.303546,...,0.083722,0.111400,0.090785,-0.000408,-0.174164,-0.115590,-0.084028,-0.007349,0.105120,0.278479
DeviceProtection,-0.002105,0.059428,0.153786,0.013963,0.360653,-0.071227,0.201137,0.275438,0.303546,1.000000,...,0.102495,0.165096,0.111554,-0.003351,-0.187373,-0.094057,-0.077286,-0.001032,0.104895,0.275230
TechSupport,-0.009212,-0.060625,0.119999,0.063268,0.324221,-0.096340,0.100571,0.354931,0.294233,0.333313,...,0.095775,0.240824,0.117272,-0.114839,-0.085509,-0.085057,-0.072049,0.006338,0.065336,0.264980
StreamingTV,-0.008393,0.105378,0.124666,-0.016558,0.279756,-0.022574,0.257152,0.176207,0.282106,0.390874,...,0.061612,0.072049,0.040433,0.144626,-0.247742,-0.068046,-0.050161,0.002006,0.095103,0.197993
StreamingMovies,-0.010487,0.120176,0.117412,-0.039741,0.286111,-0.032959,0.258751,0.187398,0.274501,0.402111,...,0.064926,0.073960,0.048575,0.137966,-0.250595,-0.060651,-0.053907,0.006559,0.087519,0.207863
PaperlessBilling,-0.011754,0.156530,-0.014877,-0.111377,0.006152,0.016505,0.163530,-0.003636,0.126735,0.103797,...,-0.051391,-0.147889,-0.013589,0.208865,-0.205398,0.012019,0.003744,-0.005126,0.007597,-0.000905
MonthlyCharges,-0.014569,0.220173,0.096848,-0.113890,0.247900,0.247398,0.490434,0.296594,0.441780,0.482692,...,0.004904,-0.074681,0.030550,0.271625,-0.377437,-0.064389,-0.046670,0.009899,0.067693,0.185840
TotalCharges,-0.000002,0.102652,0.318364,0.063593,0.825464,0.113013,0.468705,0.412091,0.509607,0.522374,...,0.170649,0.356226,0.182745,-0.059971,-0.294814,-0.254434,-0.210440,-0.047136,0.257475,0.639416
Churn,-0.008612,0.150889,-0.150448,-0.164221,-0.352229,0.011942,0.040102,-0.171226,-0.082255,-0.066160,...,-0.177820,-0.302253,-0.134302,0.301919,-0.091683,0.070623,0.020308,-0.040637,-0.121421,-0.225500
AvgCharges,-0.004415,0.093094,0.071271,-0.003358,0.077018,0.113231,0.239310,0.153270,0.219715,0.240781,...,-0.007361,0.017713,0.004449,0.109960,-0.145365,-0.042708,-0.037955,-0.008782,0.014996,0.074907
high_charge,-0.013188,0.211140,0.083615,-0.101079,0.196675,0.326834,0.480273,0.155964,0.312893,0.357641,...,-0.018950,-0.054428,0.026497,0.243332,-0.324798,-0.048111,-0.031463,0.020031,0.046466,0.148295
num_of_service,-0.017284,0.094782,0.220022,0.021907,0.523501,0.142618,0.537257,0.520518,0.597707,0.656587,...,0.115336,0.220059,0.131815,0.035155,-0.290865,-0.134868,-0.097845,-0.000315,0.139212,0.402735
InternetService_Fiber optic,-0.011286,0.255338,0.000304,-0.165818,0.019720,0.289999,0.366083,-0.030696,0.165651,0.176049,...,-0.076324,-0.211526,-0.050077,0.336410,-0.306834,-0.006584,-0.000921,0.013529,0.009777,0.006799
InternetService_No,0.006026,-0.182742,0.000615,0.139812,-0.039062,0.172209,-0.210564,-0.333403,-0.381593,-0.380754,...,0.038004,0.218278,0.001030,-0.284917,0.321361,0.010620,0.016749,-0.010965,-0.014307,-0.024871
Contract_One year,0.008026,-0.046262,0.082783,0.068368,0.202570,-0.002791,-0.003794,0.100162,0.083722,0.102495,...,1.000000,-0.289510,0.067589,-0.109130,-0.000116,-0.072638,-0.016999,0.082197,0.213270,0.016358
Contract_Two year,-0.003695,-0.117000,0.248091,0.204613,0.558533,0.003519,0.106253,0.191773,0.111400,0.165096,...,-0.289510,1.000000,0.173265,-0.282138,-0.004705,-0.144603,-0.147406,-0.107260,0.056657,0.537783
PaymentMethod_Credit card (automatic),0.001215,-0.024135,0.082029,0.060267,0.233006,-0.007721,0.060048,0.115721,0.090785,0.111554,...,0.067589,0.173265,1.000000,-0.373322,-0.286049,-0.067069,-0.039428,0.008768,0.058973,0.179415
PaymentMethod_Electronic check,0.000752,0.171718,-0.083852,-0.150642,-0.208363,0.003062,0.083618,-0.112338,-0.000408,-0.003351,...,-0.109130,-0.282138,-0.373322,1.000000,-0.387372,0.055359,0.030829,0.004303,-0.037545,-0.174797
PaymentMethod_Mailed check,0.013744,-0.153477,-0.095125,0.059071,-0.233852,-0.003319,-0.227206,-0.080798,-0.174164,-0.187373,...,-0.000116,-0.004705,-0.286049,-0.387372,1.000000,0.048015,0.049500,-0.013013,-0.083056,-0.160633
tenure_group_6-12m,0.000139,-0.014521,-0.095179,-0.038428,-0.312009,-0.002771,-0.085634,-0.080659,-0.115590,-0.094057,...,-0.072638,-0.144603,-0.067069,0.055359,0.048015,1.000000,-0.137564,-0.122067,-0.180387,-0.166640
tenure_group_1-2y,-0.000701,0.002144,-0.048868,-0.002443,-0.235469,0.012473,-0.044828,-0.055714,-0.084028,-0.077286,...,-0.016999,-0.147406,-0.039428,0.030829,0.049500,-0.137564,1.000000,-0.150962,-0.223087,-0.206086
tenure_group_2-3y,0.006196,0.027562,0.002744,0.008396,-0.030287,-0.000646,0.004482,-0.017031,-0.007349,-0.001032,...,0.082197,-0.107260,0.008768,0.004303,-0.013013,-0.122067,-0.150962,1.000000,-0.197955,-0.182870
tenure_group_3-5y,-0.018718,0.010622,0.106636,0.040337,0.361758,-0.021395,0.078732,0.075824,0.105120,0.104895,...,0.213270,0.056657,0.058973,-0.037545,-0.083056,-0.180387,-0.223087,-0.197955,1.000000,-0.270239
tenure_group_5-6y,0.016199,-0.002062,0.279545,0.116656,0.727136,0.020708,0.257768,0.262805,0.278479,0.275230,...,0.016358,0.537783,0.179415,-0.174797,-0.160633,-0.166640,-0.206086,-0.182870,-0.270239,1.000000

In [70]:
df.to_csv('churn_cleaned.csv', index=False)